{{- if .Values.memcached.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "roundcube.fullname" . }}-memcached
  labels:
    {{- include "roundcube.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
     {{- include "roundcube.selectorLabels" . | nindent 6 }}-memcached
  template:
    metadata:
      labels:
        {{- include "roundcube.selectorLabels" . | nindent 8 }}-memcached
    spec:
      containers:
        - name: {{ .Chart.Name }}-memcached
          args:
            - -vv
            - -p
            - "11211"
          image: "{{ .Values.memcached.image.repository }}:{{ .Values.memcached.image.tag }}"
          imagePullPolicy: {{ .Values.memcached.image.pullPolicy }}
          resources:
            {{- toYaml .Values.memcached.resources | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: 11211
---
# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "roundcube.fullname" . }}-memcached
  labels:
   {{- include "roundcube.labels" . | nindent 4 }}
spec:
  type: {{ .Values.memcached.service.type }}
  ports:
    - port: {{ .Values.memcached.service.port }}
      targetPort: {{ .Values.memcached.service.port }}
  selector:
    {{- include "roundcube.selectorLabels" . | nindent 4 }}-memcached
{{- end }}