apiVersion: v1
kind: Secret
metadata:
  annotations: {}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  name: roundcube-credentials
data:
  user: {{ b64enc .Values.roundcube.dbUser }}
  password: {{ b64enc .Values.roundcube.dbPassword }}
type: Opaque